### ISSUE TITLE
Warn if passed a non-Promise

### ISSUE THREAD

**Issue by mLuby** [Abazhenov/express-async-handler#12]
**Feature request**
Given warning in [the fantastic article](https://medium.com/@Abazhenov/using-async-await-in-express-with-node-8-b8af872c0016)
> An important thing to remember is when using this approach we need to have all of our async code return promises, as this approach won’t work with async callbacks that aren’t promisified.

avoid runtime error by either
1. just invoking the next function if it's not a promise, or
2. assuming it received a promise but `console.warn`ing if it is passed a non-Promise.

Happy to PR either approach. Preference for 1 but will defer to  @Abazhenov .

**Comment by josephfrazier** [comment]
Would reverting https://github.com/Abazhenov/express-async-handler/commit/36532b4f06fef54c2902ef33e3cd82d549ff6e8e address the issue by allowing the middleware to be used with synchronous callbacks?

**Comment by mLuby** [comment]
It looks like the `Promise.resolve` was still unnecessary. What I'm talking about is this: https://github.com/Abazhenov/express-async-handler/pull/14/files#diff-168726dbe96b3ce427e7fedce31bb0bc
