### ISSUE TITLE
Avoid `instanceof`, use `Promise.resolve`

### ISSUE THREAD

**Issue by glebec** [Abazhenov/express-async-handler#16]
The proper way to duck-type promises is using the static resolve, which will properly assimilate thenables. Using `instanceof` could possibly fail, e.g. with thenables or across realms (e.g. an iframe). Easy fix, if you assign me I'll do a PR later. Ciao.

**Comment by Abazhenov** [comment]
Sounds good, thanks Gabe, tell Omri I say hi!
