### ISSUE TITLE
SyntaxError only on AWS Lambda

### ISSUE THREAD

**Issue by Captnwalker1** [Abazhenov/express-async-handler#21]
I have written a lambda handler with serverless and express and testing locally everything runs great but when I upload to aws it has a syntax error:

> Syntax error in module 'index': SyntaxError
> app.get('/person', asyncHandler( async (req, res, next) => {
> __________________________________________^
> SyntaxError: Unexpected token (

Code:

> app.get('/personDevices', asyncHandler( async (req, res, next) => {
>   await pool.query("SELECT * from public.\"person\";")
>     .then(result => {
>       res.json(result.rows);
>     })
>     .catch(e => console.error(e.stack))
> }));

Am I missing an async package or something?
package.json:

> "dependencies": {
>     "async": "^2.6.0",
>     "aws-sdk": "^2.224.1",
>     "body-parser": "^1.18.2",
>     "express": "^4.16.3",
>     "express-async-handler": "^1.1.3",
>     "pg": "^7.4.1",
>     "request": "^2.85.0",
>     "serverless-http": "^1.5.5"
>   },
>   "devDependencies": {
>     "serverless-offline": "^3.20.1"
>   }

**Comment by benvogler** [comment]
What node version is your lambda running? Async/await is not supported in Node.js 6.x and I believe lambda may default to 6.10 despite 8.10 being available.

**Comment by Captnwalker1** [comment]
Derp, yeah that was the issue. Will try and switch it over to 8.10.

Thanks for the response!
