### ISSUE TITLE
Support error-handling middleware

### ISSUE THREAD

**Issue by glebec** [Abazhenov/express-async-handler#22]
https://github.com/Abazhenov/express-async-handler/blob/6de0ae78d3bdec73ca98be4ccb274275ca298747/index.js#L2

Error-handling middleware has a different function signature: `(err, req, res, next)`. This means that the position of the `next` arg depends on the handler's arity; `next` will be in position `2` for most middleware, but `3` for error handlers (functions whose `length` is `4`).

It is conceivable that people would want to do some async cleanup or actions in an error-handling middleware, so it is probably a good idea to modify this lib to account for that possibility. You'd need an `if` check that switches based on `fn.length`.

**Comment by JohannKlopp** [comment]
I was looking for a way to act differently depending on which error the await function throws.
For example: 
app.js:
`await newUser.save();`

user.js:
`var UserSchema = new mongoose.Schema({
  username: {
    type: String,
    required: true,
    unique: true,
    minlength: 1
  }(...)`

If the `newUser.find()` throws the "duplicate key" error bc the user wants to sign up with a username that is already in use (and user.js specifies `username` to be unique), then I want to be able to act on that specific error. If there's an error bs of an `email`, I would to act on that differently than I would on the username error.
