### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by curran** [Abazhenov/express-async-handler#30]
This library looks really nice to use, but I hesitate as there is no LICENSE file.

I'd suggest to use the MIT License or other permissive license.

**Comment by irohitb** [comment]
@curran  Check package.json, It is MIT license. 
Either way, it's just 6 lines of code so you can implement it by yourself also

**Comment by curran** [comment]
Oh great! Sorry, I missed the declaration in `package.json`. That covers it.
