### ISSUE TITLE
Solved

### ISSUE THREAD

**Issue by Leisa27153** [Abazhenov/express-async-handler#36]
Hi Abazhenov, I answered my own question! All good. Thank you

**Comment by jdpnielsen** [comment]
@Leisa27153 Its good practice to post the answer to your question, rather than remove the question itself. This way, other people might benefit from your work. https://xkcd.com/979

**Comment by Leisa27153** [comment]
That's smart! Will do in the future.

Thank you
Leisa

**Comment by thosil** [comment]
good practice is also to close the problem when solved
