### ISSUE TITLE
cleanup handling?

### ISSUE THREAD

**Issue by heraldb** [Abazhenov/express-async-handler#4]
Hi,
Thanks for this, very handy. I am a bit puzzled when some cleanup is needed after an error is hit. 
e.g.

router.get('/album', asyncHandler(async (req,res,next) => {
	let c = await pool.getConnection();
	let [albums] = await c.query( 'SELECT id,title FROM Aalbum ORDER BY title');
	c.release();
	res.json(albums);
}));

On purpose I misspelled the table name and the query fails. There is a useful error message, but the connection is not released (since last part of the block is not executed) and for every request a connection will stay open.
What would be your suggestion to do a cleanup after an error has taken place?

**Comment by Abazhenov** [comment]
The most straightforward solution would probably be a `try / catch` block inside of the /album `GET` route.  However, there is another thing you can do.

Say you have a collection of album endpoints.  Maybe `GET /albums`, `POST /albums`, and `GET /albums/:id`.  If you define `req.connection` in middleware beforehand and stick it on the req, you can have access to your connection inside of each of those routes, and define a custom error handler for all of them.  It might look something like this.

```js
router.use('/albums', asyncHandler(async (req, res, next) => {
  req.connection = await pool.getConnection()
  next()
}));

router.get('/albums', asyncHandler(async (req, res, next) => {
  // get albums
}));

router.post('/albums', asyncHandler(async (req, res, next) => {
  // post album
}));

router.get('/albums/:id', asyncHandler(async (req, res, next) => {
  // get album
}));

router.use((err, req, res, next) => {
  if (err) {
    req.connection.release();
    return next(err);
  }
});
```

**Comment by heraldb** [comment]
Thanks, I like this idea. Smart to use the req object to store the connection handle. 
I noticed that "req.connection" is already used, so I went for "req.db" instead. Somehow, when I use the first part of code to get a connection and store in in the req object, the request (a GET request in this case), is stalled. But getting the connection in the router.get() and store it the req object works and indeed the connection is released in case of an error. So, I suppose I can use it for all the other types of requests and have less and better readable code. Thanks!

**Comment by Abazhenov** [comment]
Ah, that was an oversight by me, calling `next()` inside of the middleware should get rid of the stalling.  Comment above is updated to reflect the change.

**Comment by heraldb** [comment]
Ah yes of course, next() was missing. Thanks!

Maybe good to update to example code above on two extra things:

1. "req.connection" is used by express, so better to use another name (I used "db") and 
2. potentially the error was raised while making the connection, so the release() would fail. I used "if (req.db) db.release()".
