### ISSUE TITLE
Unhandled promise rejection at app.param([name], callback)

### ISSUE THREAD

**Issue by 743v45** [Abazhenov/express-async-handler#41]
```javascript
router.param('id', asyncHandler(async(req, res, next, id) => {
  // UnhandledPromiseRejectionWarning: Error: oops
  throw new Error('oops');

  return next();
}));
```

https://github.com/Abazhenov/express-async-handler/blob/ccd9b5b9b0bbe853ec3374cb76ee0d7b81b736a3/index.js#L4

`next` is not last index but last function

**Comment by starmatt** [comment]
I'm using something like this instead, I think it should work for your case:

```js
export default (fn) => (...args) => {
    const next = args.filter(
        (arg) => typeof arg === 'function' && arg.name === 'next'
    )[0];

    return Promise.resolve(fn(...args)).catch(next);
};
```

**Comment by 743v45** [comment]
`(arg) => typeof arg === 'function' && (arg.name === 'next' || arg.name === 'paramCallback')`

is the way to run `router.param()`

express version is v4.17.1
